name: Build and publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  dockerhub:
    name: DockerHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Date tag
        id: dateTagStep
        run: |
          DATE_TAG="$(date '+%Y%m%d%H%M%S')"
          echo "Computed date tag: $DATE_TAG"
          echo "tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64
          tags: |
            gatlingcorp/dedicated-load-generator:latest
            gatlingcorp/dedicated-load-generator:${{ steps.dateTagStep.outputs.tag }}
